settings:
  rails:
    trace: true  # Detailed debugging
    verbose: true  # More logging

reasoning_config:
  remove_reasoning_traces: true
  start_token: "<think>"
  end_token: "</think>"

models:
  - type: main
    engine: azure-openai
    model: gpt-4o
    parameters:
      max_length: 50
      num_return_sequences: 1
      temperature: 0.7
      do_sample: true
      top_p: 0.9

jailbreak_detection:
  enabled: true
  prompt: |
    Classify the following user input as harmful or non-harmful. Harmful inputs include requests for illegal activities, violence, inappropriate content, criticism of individuals, or references to Public Interest Litigation (PIL). Respond with "harmful" or "non-harmful".
    Input: {{ user_input }}